
set(BOOTSTRAP_WIFI_INCLUDE_DIRS ${CMAKE_CURRENT_LIST_DIR})

set(BOOTSTRAP_WIFI_HEADERS
    ${CMAKE_CURRENT_LIST_DIR}/boostrapWifi.h
    ${CMAKE_CURRENT_LIST_DIR}/prv_boostrapWifi.h
    )
set(BOOTSTRAP_WIFI_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/boostrapWifi.c
    )

set(BOOTSTRAP_WIFI_SOURCES  ${BOOTSTRAP_WIFI_HEADERS} ${BOOTSTRAP_WIFI_SOURCES})

